services:
  database:
    image: postgres:16-alpine
    container_name: database
    hostname: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 5
        window: 20s
